alunos/urls.py
from django.urls import path
from alunos.views import *


app_name = 'alunos'

urlpatterns = [
    path('', listar_alunos, name = 'alunos'),
    path('novo/', form_cadastro_aluno, name='cadastrar'),
    path('cadastrar/', cadastrar_aluno, name='post'),
    path('deletar/<int:id>', deletar_aluno, name='deletar'),
    path('editar/<int:id>', form_editar_aluno, name='editar'),
    path('salvar/<int:id>', editar_aluno, name='salvar'),
]

frequencia/urls.py
from django.urls import path
from frequencia.views import *

app_name = 'frequencia'

urlpatterns = [
    path('<int:turma_id>/', lancar_frequencia_view, name='frequencia'),
    path('diarios/', diarios_view, name='diario'),
    path('relatorio/', relatorio_view, name='relatorio')
]

sistemaescolar/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('alunos/', include('alunos.urls')),
    path('turmas/', include('turmas.urls')),
    path('frequencia/', include('frequencia.urls')),
]

turmas/urls.py
from django.urls import path
from turmas.views import *

app_name = 'turmas'

urlpatterns = [
    path('', listar_turmas, name='turmas'),
    path('novo/', form_cadastrar_turma, name='cadastrar'),
    path('cadastrar/', cadastrar_turma, name = 'salvar'),
    path('deletar/<int:id>', deletar_turma, name='deletar'),
    path('editar/<int:id>', form_editar_turma, name='editar'),
    path('editarT/<int:id>', editar_turma, name='editar_turma'),
    path('detalhar/<int:id>', detalhar_turma, name='detalhar'),
    path('detalhar/<int:turma_id>/adicionarEstudante', adicionar_estudante, name='estudante'),
]

templates/partials/head.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br" id="html">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <!-- Font Ubuntu -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,500;1,700&display=swap" rel="stylesheet">
    <!-- Icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/brands.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/solid.min.css">
    <title>{{ title_page }}</title>
</head>

templates/partials/modal.html
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Cadastrar Estudante</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form action="{{form_action}}" method="post">
                    {% csrf_token %}
                    {% for field in fields %}
                    <div class="mb-3">
                        {{field}}
                    </div>
                    {% endfor %}
                    <br>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
                <button type="submit" class="btn btn-primary">Cadastrar</button>
            </div>
            </form>
        </div>
    </div>
</div>

templates/partials/modalSelect.html
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Adicionar Estudante</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form action="{{form_action}}" method="post">
                    {% csrf_token %}
                    <label for="estudante" class="p-1">Selecione um estudante:</label>
                    <select class="form-select" name="estudante_id" id="estudante">
                        {% for estudante in estudantes %}
                            <option value="{{ estudante.id }}">{{ estudante.nome }}</option>
                        {% endfor %}
                    </select>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
                <button type="submit" class="btn btn-success">Adicionar</button>
            </div>
            </form>
        </div>
    </div>
</div>

templates/partials/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">
        <i class="fa-solid fa-graduation-cap"></i>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                    aria-expanded="false">
                    Alunos
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url "alunos:cadastrar" %}">Cadastrar Estudante</a></li>
                    <li><a class="dropdown-item" href="{% url "alunos:alunos" %}">Listar Estudantes</a></li>
                </ul>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                    aria-expanded="false">
                    Turmas
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url "turmas:cadastrar" %}">Cadastrar Turmas</a></li>
                    <li><a class="dropdown-item" href="{% url "turmas:turmas" %}">Listar Turmas</a></li>
                </ul>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                    aria-expanded="false">
                    Frequência
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url "frequencia:diario" %}">Diários</a></li>
                    <li><a class="dropdown-item" href="{% url "frequencia:relatorio" %}">Relatórios</a></li>
                </ul>
            </li>
        </ul>
        <form class="d-flex" role="search">
            <div id="themeSwitcher">
                <i id="icon" class="fa-solid fa-circle-half-stroke"></i>
            </div>
            <div class="ms-3" role="button">
                <i class="fa-solid fa-circle-user" data-bs-toggle="offcanvas" data-bs-target="#offcanvasRight" aria-controls="offcanvasRight"></i>
            </div>
        </form>
      </div>
    </div>
</nav>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        const icon = document.getElementById('icon');
        const doc = document.getElementById('html');
        let theme = localStorage.getItem('theme') || 'light';

        doc.setAttribute('data-bs-theme', theme);

        themeSwitcher.addEventListener('click', function () {
            const currentTheme = doc.getAttribute('data-bs-theme');
            const newTheme = currentTheme === 'light' ? 'dark' : 'light';
            doc.setAttribute('data-bs-theme', newTheme);
            localStorage.setItem('theme', newTheme);
        });
    });

</script>

{% include "partials/offcanvaUser.html" %}

templates/partials/offcanvaUser.html
<div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel">
    <div class="offcanvas-header">
      <h5 class="offcanvas-title" id="offcanvasRightLabel">Bem-Vindo, Henrique</h5>
      <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
        <div class="d-flex justify-content-center">
          <div class="avatar">
            <h1 class="d-flex justify-content-center mt-4" id="username"></h1>
          </div>
        </div>
        <i class="fa-solid fa-right-from-bracket"> Sair</i>
    </div>
</div>

<script>
    let username = document.getElementById("username");
    let nomeSession = "Henrique Venâncio dos Santos";
    const names = nomeSession.split(" ");
    username.innerHTML = names[0].slice(0, 1) + names[1].slice(0, 1)
</script>