alunos/urls.py
from django.urls import path
from alunos.views import *


app_name = 'alunos'

urlpatterns = [
    path('', listar_alunos, name = 'alunos'),
    path('novo/', form_cadastro_aluno, name='cadastrar'),
    path('cadastrar/', cadastrar_aluno, name='post'),
    path('deletar/<int:id>', deletar_aluno, name='deletar'),
    path('editar/<int:id>', form_editar_aluno, name='editar'),
    path('salvar/<int:id>', editar_aluno, name='salvar'),
]

frequencia/urls.py
from django.urls import path
from frequencia.views import *

app_name = 'frequencia'

urlpatterns = [
    path('<int:turma_id>/', lancar_frequencia_view, name='frequencia'),
    path('diarios/', diarios_view, name='diario'),
    path('relatorio/', relatorio_view, name='relatorio')
]

sistemaescolar/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('alunos/', include('alunos.urls')),
    path('turmas/', include('turmas.urls')),
    path('frequencia/', include('frequencia.urls')),
]

turmas/urls.py
from django.urls import path
from turmas.views import *

app_name = 'turmas'

urlpatterns = [
    path('', listar_turmas, name='turmas'),
    path('novo/', form_cadastrar_turma, name='cadastrar'),
    path('cadastrar/', cadastrar_turma, name = 'salvar'),
    path('deletar/<int:id>', deletar_turma, name='deletar'),
    path('editar/<int:id>', form_editar_turma, name='editar'),
    path('editarT/<int:id>', editar_turma, name='editar_turma'),
    path('detalhar/<int:id>', detalhar_turma, name='detalhar'),
    path('detalhar/<int:turma_id>/adicionarEstudante', adicionar_estudante, name='estudante'),
]

alunos/models.py
from django.db import models


class Aluno(models.Model):
    matricula = models.CharField(max_length=10, null=True)
    nome = models.CharField(max_length=100)
    email = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.nome

frequencia/models.py
from django.db import models
from alunos.models import Aluno
from aula.models import Aula


class Frequencia(models.Model):
    aluno = models.ForeignKey(Aluno, on_delete=models.CASCADE, related_name="frequencias")
    aula = models.ForeignKey(Aula, on_delete=models.CASCADE, related_name="aulas")
    presente = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.aluno.nome} - {'Presente' if self.presente else 'Falta'}"

turmas/models.py
from django.db import models
from alunos.models import Aluno

class Turma(models.Model):
    nome = models.CharField(max_length=50)
    horario = models.CharField(max_length=50)
    descricao = models.CharField(max_length=100)
    estudantes = models.ManyToManyField(Aluno)


    def __str__(self):
        return f'{self.nome} - {self.estudantes}'

alunos/forms.py
from django import forms
from .models import Aluno


class AlunoForm(forms.ModelForm):

    class Meta:
        model = Aluno
        fields = ['nome', 'matricula', 'email']

    nome = forms.CharField(
        required=True,
        label='Nome Completo',
        widget= forms.TextInput(attrs={
            'placeholder':'Nome Completo',
            'class': 'form-control',
        }),
    )

    matricula = forms.CharField(
        required=True,
        label='Matrícula',
        widget= forms.TextInput(attrs={
            'placeholder':'Matrícula',
            'class': 'form-control',
        }),
    )

    email = forms.CharField(
        required=True,
        label='E-mail Institucional',
        widget= forms.TextInput(attrs={
            'placeholder':'E-mail Institucional',
            'class': 'form-control',
        }),
    )

frequencia/forms.py
from django import forms
from .models import Frequencia

class FrequenciaForm(forms.ModelForm):
    class Meta:
        model = Frequencia
        fields = ['aluno', 'data', 'presente']

turmas/forms.py
from django import forms
from .models import Turma


class TurmaForm(forms.ModelForm):

    class Meta:
        model = Turma
        fields = ['nome', 'descricao', 'horario']

    nome = forms.CharField(
        required = True,
        label = 'Título da Turma',
        widget = forms.TextInput(attrs={
            'placeholder': 'Título da Turma',
            'class': 'form-control',
        }),
    )

    descricao = forms.CharField(
        required = True,
        label = 'Descrição da Turma',
        widget = forms.TextInput(attrs={
            'placeholder': 'Descrição da Turma',
            'class': 'form-control',
        }),
    )

    horario = forms.CharField(
        required = True,
        label = 'Horário de Aula',
        widget = forms.TextInput(attrs={
            'placeholder': 'Horário de Aula',
            'class': 'form-control',
        }),
    )

alunos/views.py
from django.shortcuts import render, redirect
from django.http import Http404
from django.urls import reverse
from .forms import AlunoForm
from .models import Aluno


def listar_alunos(request):
   
   alunos = Aluno.objects.all()
   form = AlunoForm()
   return render(request, 'pages/alunos.html', {
      'alunos': alunos,
      'fields' : form,
      'form_action' : reverse('alunos:post')
   })


def form_cadastro_aluno(request):
   form = AlunoForm()
   return render(request, 'pages/formCadastro.html', {
      'title': 'Cadastro de Estudante',
      'fields' : form,
      'form_action' : reverse('alunos:post')
   })


def cadastrar_aluno(request):
   
   if not request.POST:
      raise Http404()
   
   aluno = AlunoForm(request.POST)
   if aluno.is_valid():
      nome = aluno.cleaned_data.get('nome', '')
      matricula = aluno.cleaned_data.get('matricula', '')
      email = aluno.cleaned_data.get('email', '')
      Aluno.objects.create(nome=nome, email=email, matricula=matricula)
      
   return redirect(reverse('alunos:alunos'))


def deletar_aluno(request, id):
   aluno = Aluno.objects.get(id = id)
   aluno.delete()
   return redirect(reverse('alunos:alunos'))


def form_editar_aluno(request, id):
   aluno = Aluno.objects.get(id = id)
   form = AlunoForm(instance = aluno)
   return render(request, 'pages/formEditar.html', {
      'aluno' : aluno,
      'title': 'Editar Estudante',
      'fields' : form,
      'form_action' : reverse('alunos:salvar', args=[aluno.id])
   })


def editar_aluno(request, id):
   
   aluno = AlunoForm(request.POST)
   if aluno.is_valid():
      nome = aluno.cleaned_data.get('nome', '')
      matricula = aluno.cleaned_data.get('matricula', '')
      email = aluno.cleaned_data.get('email', '')
      aluno = Aluno.objects.get(id = id)
      aluno.nome = nome
      aluno.matricula = matricula
      aluno.email = email
      aluno.save()

   return redirect(reverse('alunos:alunos'))

   

frequencia/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.utils import IntegrityError
from django.core.exceptions import ObjectDoesNotExist
from frequencia.models import Frequencia
from turmas.models import Turma
from aula.models import Aula


def lancar_frequencia_view(request, turma_id):
    try:
        turma = get_object_or_404(Turma, id=turma_id)
        alunos = turma.estudantes.all().order_by('nome')

        if request.method == 'POST':
            
            conteudo = request.POST.get('conteudo')
            data = request.POST.get('data')
            aula = Aula.objects.create(
                turma = turma,
                data = data,
                conteudo = conteudo
            )
            
            for aluno in alunos:
                presente = request.POST.get(f'presente_{aluno.id}') == 'on'
                Frequencia.objects.update_or_create(
                    aluno=aluno,
                    defaults={'presente': presente},
                    aula = aula
                )

            return redirect('frequencia:diario')

        return render(request, 'pages/frequencia.html', {
            'turma': turma,
            'alunos': alunos,
        })
    
    except IntegrityError:
        return render(request, 'pages/erro.html', {
            'mensagem' : 'Ops! A frequência da turma já foi registrada para hoje. Se precisar fazer alguma correção, entre em contato com o administrador.'
        })


def diarios_view(request):

    try:

        turmas = Turma.objects.all().order_by('nome')
        frequencia = []
        aula = None


        if request.method == 'POST':
            turma = request.POST.get('turma_id')
            data = request.POST.get('data')
            aula = Aula.objects.get(data = data, turma = turma)
            frequencia = Frequencia.objects.filter(aula = aula)
            print(frequencia)
        return render(request, 'pages/diario.html', {
            'turmas' : turmas,
            'frequencia' : frequencia,
            'aula': aula
        })
    
    except ObjectDoesNotExist:
        return render(request, 'pages/erro.html', {
            'mensagem' : 'Ops! Não existe nenhum diário para essa turma nesta data!'
        })
    

def relatorio_view(request):
    
    turmas = Turma.objects.all()
    turma = None
    aulas = []
    alunos = []
    frequencias = []
    frequencias_dict = {}
    if request.method == 'POST':
        turma_id = request.POST.get('turma_id')
        aulas = Aula.objects.filter(turma = turma_id).all().order_by('data')
        turma = Turma.objects.filter(id = turma_id).first()
        alunos = turma.estudantes.all().order_by('nome')
        frequencias_dict = {aluno.nome : [] for aluno in alunos}
        
        for aula in aulas:
            freq = Frequencia.objects.filter(aula = aula).all()
            frequencias.append(freq)

        
        for frequencia in frequencias:
            for x in frequencia:
                frequencias_dict[x.aluno.nome].append(x.presente)

    return render(request, 'pages/relatorio.html', {
        'turmas' : turmas,
        'aulas' : aulas,
        'alunos': alunos,
        'frequencias' : frequencias_dict,
        'turma' : turma
    })

turmas/views.py
from django.shortcuts import render, redirect
from django.http import Http404
from django.urls import reverse
from .models import Turma, Aluno
from .forms import TurmaForm


def listar_turmas(request):
    turmas = Turma.objects.all()
    return render(request, 'pages/turmas.html', {
        'turmas': turmas
    })


def form_cadastrar_turma(request):
    form = TurmaForm()
    return render(request, 'pages/formCadastro.html', {
        'fields': form,
        'title': 'Cadastro de Turma',
        'form_action': reverse('turmas:salvar')
    })


def cadastrar_turma(request):
    
    if not request.POST:
        raise Http404()

    turma = TurmaForm(request.POST)

    if turma.is_valid():
        nome = turma.cleaned_data.get('nome', '')
        descricao = turma.cleaned_data.get('descricao', '')
        horario = turma.cleaned_data.get('horario', '')
        Turma.objects.create(
            nome = nome,
            descricao = descricao,
            horario = horario
        )
    return redirect(reverse('turmas:turmas'))


def deletar_turma(request, id):

    turma = Turma.objects.get(id = id)
    turma.delete()
    return redirect(reverse('turmas:turmas'))


def form_editar_turma(request, id):

    turma = Turma.objects.get(id = id)
    form = TurmaForm(instance=turma)
    return render(request, 'pages/formEditar.html', {
        'turma': turma,
        'fields' : form,
        'title' : 'Editar Dados da Turma',
        'form_action' : reverse('turmas:editar_turma', args=[turma.id])
    })


def editar_turma(request, id):

    turma = TurmaForm(request.POST)

    if turma.is_valid():
        nome = turma.cleaned_data.get('nome', '')
        descricao = turma.cleaned_data.get('descricao', '')
        horario = turma.cleaned_data.get('horario', '')
        turma = Turma.objects.get(id = id)
        turma.nome = nome
        turma.descricao = descricao
        turma.horario = horario
        turma.save()

    return redirect(reverse('turmas:turmas'))


def detalhar_turma(request, id):

    turma = Turma.objects.get(id = id)
    alunos = turma.estudantes.all().order_by('nome')
    estudantes = Aluno.objects.exclude(turma=turma) 

    return render(request, 'pages/detalharTurma.html', {
        'turma': turma,
        'estudantes': estudantes,
        'alunos' : alunos,
        'form_action': reverse('turmas:estudante', args=[turma.id])
    })


def adicionar_estudante(request, turma_id):

    turma = Turma.objects.get(id = turma_id)

    if request.method == "POST":
        estudante_id = request.POST.get("estudante_id")
        estudante = Aluno.objects.get(id = estudante_id)

        turma.estudantes.add(estudante)

        return redirect(reverse('turmas:detalhar', args=[turma.id]))
    
    return render(request, "detalharTurma.html", {
        "turma": turma
    })

templates/pages/alunos.html
{% include "partials/head.html" %}

<body>
    
    {% include 'partials/navbar.html' %}

    <div class="container mt-5">
        <h3 class="mb-5">Estudantes Cadastrados</h3>
        <table class="table table-striped table-bordered border-secundary text-center">
            <thead>
                <tr>
                    <th>Matrícula</th>
                    <th>Aluno</th>
                    <th>E-mail Institucional</th>
                    <th>Opções</th>
                </tr>
            </thead>
            <tbody>
                {% for aluno in alunos %}
                <tr>
                    <th>{{ aluno.matricula }}</th>
                    <th>{{ aluno.nome }}</th>
                    <th>{{ aluno.email }}</th>
                    <th class="icons">
                        <a href="editar/{{aluno.id}}">
                            <i class="fa-solid fa-pencil pencil"></i>
                        </a>
                        <a href="deletar/{{aluno.id}}">
                            <i class="fas fa-trash trash"></i>
                        </a>
                    </th>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        {% include 'partials/modal.html' %}

        <div class="mt-4 modal-button" data-bs-toggle="modal" data-bs-target="#exampleModal">
            <i class="far fa-plus-square icon"></i>
            Cadastrar Aluno
        </div>
    </div>
</body>
</html>

templates/pages/cadastroAluno.html
{% include "partials/head.html" %}

<body>
    
    {% include 'partials/navbar.html' %}

    <div class="container mt-5">
        <h3 class="mb-5">Cadastar Estudante</h3>
        <div>
            <form action="{{form_action}}" method="post">
                {% csrf_token %}
                {% for field in fields %}
                <div class="mb-3">
                    {{field}}
                </div>
                {% endfor %}
                <br>
        </div>
            <button type="submit" class="btn btn-primary">Cadastrar</button>
        </form>
    </div>
</body>
</html>

templates/pages/detalharTurma.html
{% include 'partials/head.html' %}

{% include 'partials/navbar.html' %}

<div class="container mt-4">

    <h3 class="mb-4">Turma</h3>
    <table class="table table-striped table-bordered border-secundary text-center">
        <tr>
            <th>Nome</th>
            <td>{{ turma.nome }}</td>
        </tr>
        <tr>
            <th>Horário</th>
            <td>{{ turma.horario }}</td>
        </tr>
        <tr>
            <th>Descrição</th>
            <td>{{ turma.descricao }}</td>
        </tr>
    </table>

    <a href="{% url "frequencia:frequencia" turma.id %}" class="icon">
        <div class="mt-4 modal-button">
            <i class="fa-regular fa-id-card"></i>
            Lançar Frequência
        </div>
    </a>

    {% include 'partials/modalSelect.html' %}

    <h3 class="mt-5">Estudantes</h3>

    <div class="mt-4 modal-button" data-bs-toggle="modal" data-bs-target="#exampleModal">
        <i class="far fa-plus-square icon"></i>
        Adicionar Estudante
    </div>

    <table class="table table-striped table-bordered mt-3">
        <!-- <thead>
            <tr>
                <th>Alunos</th>
            </tr>
        </thead> -->
        <tbody>
            {% for aluno in alunos %}
            <tr>
                <th>{{ aluno.nome }}</th>
            </tr>
            {% endfor %}
        </tbody>
    </table>

</div>
</html>

templates/pages/diario.html
{% include 'partials/head.html' %}

{% include 'partials/navbar.html' %}

<div class="container">
    <h3 class="mt-5 mb-3">Diário de Aula</h3>
    <form action="" method="post">
        {% csrf_token %}
        <div class="row g-2">
            <div class="col-md">
                <select class="form-select" name="turma_id" id="turma">
                    {% for turma in turmas %}
                    <option value="{{ turma.id }}">{{ turma.nome }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="col-md">
                <input type="date" class="form-control" name="data" required="true">
            </div>
        </div>
        <div class="mt-3">
            <button type="submit" class="btn btn-success" >Buscar Diário</button>
        </div>
    </form>
    
    <div class="accordion accordion-flush border mt-3 mb-3" id="accordionFlushExample">
        <div class="accordion-item">
          <h2 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
              Detalhes da Aula
            </button>
          </h2>
          <div id="flush-collapseOne" class="accordion-collapse collapse" data-bs-parent="#accordionFlushExample" style="">
            <div class="accordion-body">
                Número de Presentes: {{frequencia|length}}
            </div>
            <div class="accordion-body">
                Conteúdo: {{aula.conteudo}}
            </div>
          </div>
        </div>
    </div>

    <table class="table table-striped table-bordered border-secundary text-center">
        <thead>
            <th>Aluno</th>
            <th>Situação</th>
        </thead>
        <tbody>
            {% for f in frequencia %}
            <tr>
                <th>{{f.aluno.nome}}</th>
                {% if f.presente %}
                <th>Presente</th>
                {% else %}
                <th>Falta</th>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

templates/pages/editarAluno.html
{% include "partials/head.html" %}

<body>
    
    {% include 'partials/navbar.html' %}

    <div class="container mt-5">
        <h3 class="mb-5">Editar Estudante</h3>
        <div>
            <form action="{{form_action}}" method="post">
                {% csrf_token %}
                {% for field in fields %}
                <div class="mb-3">
                    {{field}}
                </div>
                {% endfor %}
                <br>
        </div>
            <button type="submit" class="btn btn-primary">Salvar Alterações</button>
        </form>
    </div>
</body>
</html>

templates/pages/erro.html
{% include 'partials/head.html' %}

{% include 'partials/navbar.html' %}

<div class="container mt-5">
    <div class="alert alert-warning" role="alert">
        {{mensagem}}
    </div>
</div>

templates/pages/formCadastro.html
{% include "partials/head.html" %}

<body>
    
    {% include 'partials/navbar.html' %}

    <div class="container mt-5">
        <h3 class="mb-5">{{title}}</h3>
        <div>
            <form action="{{form_action}}" method="post">
                {% csrf_token %}
                {% for field in fields %}
                <div class="mb-3">
                    {{field}}
                </div>
                {% endfor %}
                <br>
        </div>
            <button type="submit" class="btn btn-primary">Cadastrar</button>
        </form>
    </div>
</body>
</html>

templates/pages/formEditar.html
{% include "partials/head.html" %}

<body>
    
    {% include 'partials/navbar.html' %}

    <div class="container mt-5">
        <h3 class="mb-5">{{title}}</h3>
        <div>
            <form action="{{form_action}}" method="post">
                {% csrf_token %}
                {% for field in fields %}
                <div class="mb-3">
                    {{field}}
                </div>
                {% endfor %}
                <br>
        </div>
            <button type="submit" class="btn btn-primary">Salvar Alterações</button>
        </form>
    </div>
</body>
</html>

templates/pages/frequencia.html
{% include 'partials/head.html' %}

{% include 'partials/navbar.html' %}

{% block content %}

<div class="container mt-4">
    <table class="table table-striped table-bordered border-secundary text-center">
        <thead>
            <tr>
                <th>{{turma.nome}}</th>
                <th>{{turma.horario}}</th>
                <th>{{turma.descricao}}</th>
            </tr>
        </thead>
    </table>

    <h3 class="mt-3 mb-3">Registro de Frequência</h3>
    <form method="POST">
        {% csrf_token %}
        <div class="row g-2">
            <div class="col-md">
                <input type="text" class="form-control" placeholder="Conteúdo da Aula" name="conteudo" required="true">
            </div>
            <div class="col-md">
                <input type="date" class="form-control" placeholder="Data" name="data" required="true">
            </div>
        </div>
        <table class="table table-striped table-bordered mt-3 text-center">
            <tr>
                <th>Aluno</th>
                <th>Presente</th>
            </tr>
            {% for aluno in alunos %}
            <tr>
                <td>{{ aluno.nome }}</td>
                <td>
                    <input type="checkbox" name="presente_{{ aluno.id }}" {% if aluno.id in frequencias %}checked{% endif %} checked>
                </td>
            </tr>
            {% endfor %}
        </table>
        <button class="btn btn-success" type="submit">Salvar Frequência</button>
    </form>
</div>
{% endblock %}

templates/pages/relatorio.html
{% load static %}
{% include 'partials/head.html' %}
{% include 'partials/navbar.html' %}

<div class="container mt-5" id="tabela">

    <h3 class="mt-3 mb-3 print">Relatório de Frequência por Turma</h3>
    <form action="" method="post" class="print">
        {% csrf_token %}
        <div>
            <select class="form-select" name="turma_id" id="turma">
                {% for turma in turmas %}
                <option value="{{ turma.id }}">{{ turma.nome }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="mt-3">
            <button type="submit" class="btn btn-success print">Detalhar</button>
        </div>
    </form>

    {% if frequencias %}
    <h3 class="mt-3 mb-3">{{turma.nome}}</h3>
    <table class="table table-striped table-bordered border-secundary text-center mt-3" >
        <thead>
            <th>Aluno</th>
            {% for aula in aulas %}
                <th>{{aula.data | date:"d/m/Y" }}</th>
            {% endfor %}
            </tr>
        </thead>
        <tbody>
            {% for aluno, presencas in frequencias.items %}
                <tr>
                    <td>{{ aluno }}</td>
                    {% for presenca in presencas %}
                    {% if presenca %}
                        <td>P</td>
                    {% else %}
                        <td>F</td>
                    {% endif %}
                    {% endfor %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <script src="{% static 'js/script.js' %}"></script>
    <button class="btn btn-success print" onclick="imprimirTabela('tabela')">Imprimir</button>
    {% endif %}
</div>
</html>

templates/pages/turmas.html
{% include 'partials/head.html' %}

{% include 'partials/navbar.html' %}

<div class="container text-center mt-5">
    <div class="row justify-content-evenly">
        {% for turma in turmas %}
        <div class="col-6 mb-5">
            <div class="card">
                <div class="card-header">
                    {{turma.nome}}
                </div>
                <div class="card-body">
                    <h5 class="card-title">{{turma.horario}}</h5>
                    <p class="card-text">{{turma.descricao}}</p>
                </div>
                <div class="card-header icons">
                    <a href="detalhar/{{turma.id}}">
                        <i class="fa-solid fa-people-group people"></i>
                    </a>
                    <a href="editar/{{turma.id}}">
                        <i class="fa-solid fa-pencil pencil"></i>
                    </a>
                    <a href="deletar/{{turma.id}}">
                        <i class="fas fa-trash trash"></i>
                    </a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>